(define (problem p1)
	(:domain hanoi)
	(:objects d1 d2 d3 d4 d5 - disk)
	(:init
		(mniejszy d1 d2) 
		(mniejszy d1 d3)
		(mniejszy d1 d4)
		(mniejszy d1 d5)
		(mniejszy d2 d3)
		(mniejszy d2 d4)
		(mniejszy d2 d5)
		(mniejszy d3 d4)
		(mniejszy d3 d5)
		(mniejszy d4 d5)
		(napaliku x d1) 
		(napaliku x d2)
		(napaliku x d3)
		(napaliku x d4)
		(napaliku x d5)
	)
	(:goal 
		(and
			(napaliku z d1)
			(napaliku z d2)
			(napaliku z d3)
			(napaliku z d4)
			(napaliku z d5)
		)
	)
)